---
title: "Preparing and Cleaning the Data"
author: "Meisam Omidi"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
## Load packages
library(leaps)
library(corrplot)
library(devtools)
library(VIM)
library(pscl)
library(ResourceSelection)
library(HH)
library(pscl)
library(ggplot2)
library(gridExtra)
library(scales)
library(tidyr)
library(dplyr)
library(readr)
library(ggformula)
library(imputeMissings)
library(DMwR2)
library(see)
library(imputeMissings)
library(gapminder)
library(caret)
library(rpart) 
library(rattle)
```

## Load data

```{r echo=TRUE, message=FALSE, warning=FALSE}
diabetes <- read.csv("diabetes.csv", header=TRUE, sep=",", stringsAsFactors = FALSE)
diabetes_0 <-diabetes

summary(diabetes)
 
```

## Preparing and Cleaning the Data

              
```{r echo=TRUE, message=FALSE, warning=FALSE}
 # to substitute missing data with NA
diabetes_0 <- mutate(diabetes_0, Glucose = ifelse(Glucose == 0, NA, Glucose), BloodPressure = ifelse(BloodPressure == 0, NA, BloodPressure), SkinThickness = ifelse(SkinThickness == 0, NA, SkinThickness), Insulin = ifelse(Insulin == 0, NA, Insulin), BMI = ifelse(BMI == 0, NA, BMI), Age = ifelse(Age == 0, NA, Age))



```
  
```{r echo=FALSE, message=FALSE, warning=FALSE}
# to calculate missing data percentage 

library(VIM)
aggr(diabetes_0, numbers=TRUE, sortVars=TRUE, cex.axis=.7, gap=3, 
     ylab=c("Proportion of missingness","Missingness Pattern"))





# The correlation plot to Check the correlation between variables
diabetes_1_num <- diabetes_0
diabetes_1_num$Outcome <- NULL
diabetes_1_num$Insulin <- NULL
diabetes_1_num$SkinThickness <- NULL

corrmatrix <- cor(diabetes_1_num)
corrplot::corrplot(corrmatrix, method="shade", type = "upper",tl.cex=.6	
, tl.col="black", title="Correlation Plot",number.font = 2, mar=c(0,0,1,0),	)


diab_0 <- diabetes_0


diab_0$Outcome <- as.factor(diab_0$Outcome)

par(mfrow=c(2 ,2))

diab_0 %>% gf_boxplot(Pregnancies~Outcome) %>%   
  gf_labs(x = "Diabetes",  
    y = "Number of pregnant") %>%   
  gf_theme(axis.text = element_text(size = 12),
           axis.title = element_text(size = 12),
        legend.title=element_text(size=14), 
    legend.text=element_text(size=9))

QQlabels = c("0" = "Outcome=0","1" = "Outcome=1")
ggplot(data = diab_0, aes(sample=Pregnancies)) + 
    stat_qq() + 
    stat_qqline() + 
    facet_grid(.~Outcome,labeller=labeller(Outcome=QQlabels))


diab_0 %>% gf_boxplot(Glucose~Outcome) %>%   
  gf_labs(x = "Diabetes",  # hide labeling
    y = "Plasma Glucose Concentration") %>%   
  gf_theme(axis.text = element_text(size = 12),
           axis.title = element_text(size = 12),
        legend.title=element_text(size=14), 
    legend.text=element_text(size=9))

QQlabels = c("0" = "Outcome=0","1" = "Outcome=1")
ggplot(data = diab_0, aes(sample=Glucose)) + 
    stat_qq() + 
    stat_qqline() + 
    facet_grid(.~Outcome,labeller=labeller(Outcome=QQlabels))


diab_0 %>% gf_boxplot(BloodPressure~Outcome) %>%   
  gf_labs(x = "Diabetes",  # hide labeling
    y = "Blood Pressure") %>%   
  gf_theme(axis.text = element_text(size = 12),
           axis.title = element_text(size = 12),
        legend.title=element_text(size=14), 
    legend.text=element_text(size=9))

QQlabels = c("0" = "Outcome=0","1" = "Outcome=1")
ggplot(data = diab_0, aes(sample=BloodPressure)) + 
    stat_qq() + 
    stat_qqline() + 
    facet_grid(.~Outcome,labeller=labeller(Outcome=QQlabels))

diab_0 %>% gf_boxplot(BMI~Outcome) %>%   
  gf_labs(x = "Diabetes",  # hide labeling
    y = "BMI") %>%   
  gf_theme(axis.text = element_text(size = 12),
           axis.title = element_text(size = 12),
        legend.title=element_text(size=14), 
    legend.text=element_text(size=9))

QQlabels = c("0" = "Outcome=0","1" = "Outcome=1")
ggplot(data = diab_0, aes(sample=BMI)) + 
    stat_qq() + 
    stat_qqline() + 
    facet_grid(.~Outcome,labeller=labeller(Outcome=QQlabels))

diab_0 %>% gf_boxplot(Age~Outcome) %>%   
  gf_labs(x = "Diabetes",  # hide labeling
    y = "Age") %>%   
  gf_theme(axis.text = element_text(size = 12),
           axis.title = element_text(size = 12),
        legend.title=element_text(size=14), 
    legend.text=element_text(size=9))

QQlabels = c("0" = "Outcome=0","1" = "Outcome=1")
ggplot(data = diab_0, aes(sample=Age)) + 
    stat_qq() + 
    stat_qqline() + 
    facet_grid(.~Outcome,labeller=labeller(Outcome=QQlabels))


diab_0 %>% gf_boxplot(DiabetesPedigreeFunction~Outcome) %>%   
  gf_labs(x = "Diabetes",  # hide labeling
    y = "DiabetesPedigreeFunction") %>%   
  gf_theme(axis.text = element_text(size = 12),
           axis.title = element_text(size = 12),
        legend.title=element_text(size=14), 
    legend.text=element_text(size=9))

QQlabels = c("0" = "Outcome=0","1" = "Outcome=1")
ggplot(data = diab_0, aes(sample=DiabetesPedigreeFunction)) + 
    stat_qq() + 
    stat_qqline() + 
    facet_grid(.~Outcome,labeller=labeller(Outcome=QQlabels))


table(diab_0$Outcome)
ccu <- na.omit(diab_0)
table(ccu$Outcome)
```


```{r}
diab_0 %>%
  gf_histogram(~Pregnancies)
diab_0 %>%
  gf_histogram(~BMI)   
diab_0 %>%
  gf_histogram(~DiabetesPedigreeFunction)
diab_0 %>%
  gf_histogram(~Age)   

#     The logarithm transformation 

diab_0$Pregnancies  <- log10(diab_0$Pregnancies+1)
diab_0$BMI  <- log10(diab_0$BMI)
diab_0$DiabetesPedigreeFunction  <- log10(diab_0$DiabetesPedigreeFunction)
diab_0$Age  <- log10(diab_0$Age)

diab_0 %>%
  gf_histogram(~Pregnancies)
diab_0 %>%
  gf_histogram(~BMI)   
diab_0 %>%
  gf_histogram(~DiabetesPedigreeFunction)
diab_0 %>%
  gf_histogram(~Age)   


diab_0 %>% gf_boxplot(Pregnancies~Outcome) %>%   
  gf_labs(x = "Diabetes",  # hide labeling
    y = "Number of pregnant") %>%   
  gf_theme(axis.text = element_text(size = 12),
           axis.title = element_text(size = 12),
        legend.title=element_text(size=14), 
    legend.text=element_text(size=9))

QQlabels = c("0" = "Outcome=0","1" = "Outcome=1")
ggplot(data = diab_0, aes(sample=Pregnancies)) + 
    stat_qq() + 
    stat_qqline() + 
    facet_grid(.~Outcome,labeller=labeller(Outcome=QQlabels))


diab_0 %>% gf_boxplot(BMI~Outcome) %>%   
  gf_labs(x = "Diabetes",  # hide labeling
    y = "BMI") %>%   
  gf_theme(axis.text = element_text(size = 12),
           axis.title = element_text(size = 12),
        legend.title=element_text(size=14), 
    legend.text=element_text(size=9))

QQlabels = c("0" = "Outcome=0","1" = "Outcome=1")
ggplot(data = diab_0, aes(sample=BMI)) + 
    stat_qq() + 
    stat_qqline() + 
    facet_grid(.~Outcome,labeller=labeller(Outcome=QQlabels))

diab_0 %>% gf_boxplot(Age~Outcome) %>%   
  gf_labs(x = "Diabetes",  # hide labeling
    y = "Age") %>%   
  gf_theme(axis.text = element_text(size = 12),
           axis.title = element_text(size = 12),
        legend.title=element_text(size=14), 
    legend.text=element_text(size=9))

QQlabels = c("0" = "Outcome=0","1" = "Outcome=1")
ggplot(data = diab_0, aes(sample=Age)) + 
    stat_qq() + 
    stat_qqline() + 
    facet_grid(.~Outcome,labeller=labeller(Outcome=QQlabels))


diab_0 %>% gf_boxplot(DiabetesPedigreeFunction~Outcome) %>%   
  gf_labs(x = "Diabetes",  # hide labeling
    y = "DiabetesPedigreeFunction") %>%   
  gf_theme(axis.text = element_text(size = 12),
           axis.title = element_text(size = 12),
        legend.title=element_text(size=14), 
    legend.text=element_text(size=9))

QQlabels = c("0" = "Outcome=0","1" = "Outcome=1")
ggplot(data = diab_0, aes(sample=DiabetesPedigreeFunction)) + 
    stat_qq() + 
    stat_qqline() + 
    facet_grid(.~Outcome,labeller=labeller(Outcome=QQlabels))

```
